project:
  type: website
  output-dir: docs

website:
  title: "Patient Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scripts.qmd
        text: Scripts
      - href: slides.qmd
        text: Slides
      - href: patient_education_plan.qmd
        text: Plan
      - href: https://www.youtube.com/channel/UC5Deez8jUMnLhcf72-cHA7Q
        text: YouTube

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

