project:
  type: website
  output-dir: docs

website:
  title: "Patient Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides.qmd
        text: Slides

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

