---
title: "Workflow"
---

# Current Workflow

Slideshow created in Keynote with script in Notes section. Keynote files are stored in iCloud

## Connections:

Yeti USB-A plugs into LionWei hub-\> plugs into USB-C on Macbook Air 15

HDMI from Lumex to acer USB 3.0 capture -\> plugs into USC-A on LionWei

LionWei -\> plugs into USB-C on Macbook Air 15

## Generate scripts as .docx files for use in the teleprompter

KeyNoteMarkdown_3 script (Script Editor) is used to create a markdown file extracted from Keynote. The desired Keynote file must be in the active window.

Run KeyNoteMarkdown_3. Choose No to extract context. This creates a markdown (.md) file in jcsal/Documents/PatientEducation/patient_education/keynote_scripts

RStudio opens project patient_education.

`git add –all`

`git add commit -m 'commit message`

`git push origin main`

Open Safari in iPad and point to https://jcsalo.github.io/patient_education/scripts.htm

Download the appropriate script as a .docx file. This is stored under Files \>\>Downloads

Open the S-Teleprompter app and choose "Import File" to open the script .docx file. This is then saved as a script file

Teleprompter remote is used to control S-Teleprompter app placed into the teleprompter

Trigger: start and stop scrolling. A and Y control speed of scrolling. Turn on with power button on left-hand side

## Set up Keynote to broadcast within network using NDI

- Open presentation in KeyNote. Select Play \>\> In Window.

- Play presentation

- Open NDI Scan Converter and find the Keynote file

- NDI Scan Converting is now broadcasting Keynote images within network

## OBS

In Macbook Air15:

- Open OBS

- go to Scene 8-Keynote.

- Reset sources:

  - Reset NDI images by selecting NDI Source 2 and selecting NDI Air a13

  - Reset Lumix via USB after connecting HDMI output from Lumex camert to Acer USB 3.0 capture card to USB-D input on Air15.

  - Reset source for "Yeti Blue"

- on wireless keyboard: hotkey 8 for slides only (- via NDI) and hotkey 9 for overlay

- Hotkey "L" (lowercase) toggles lower third "Jonathan Salo MD Cancer Surgeon"

## Adjust Keynote Broadcasting

The size of the Keynote broadcast image is usually incorrect. Select the Keynote Scene (tap 8) on OBS. Adjust the size of the Keynote presentation on Macbook Air13 to precisely fill the screen of OBS on Air15

## White Balance

Center camera on gray card Press WB key on back of camera Set. to WB1 Click set (tap screen)

## Lamp setup

Speaker Left - Octagon soft light on stand

Speaker Right - Octagon soft light on desk stand + Neewer LED light turned against the wall

## Recording

MacBook Air15 keyboard on a plastic box. Macbook Air13 on a music stand (or Air13 keyboard on music stand)

hotkeys:

8- Keynote (slide only)

9 - Overlay

0 Keypad: Start recording . (del) Keypad: Pause and Unpause recording O Keypad: May toggle start stop

Green Screen setting

Default color 388 127 207

Color picked Dec 07 Color 70a056 15 100 217

Videos are stored in jcsal \>\> Movies

## Atrium Health

Teal is 00818A
