---
title: "Christmas 2024"
format: 
  pptx: 
    reference-doc: template.pptx
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    css: "lci_styles.css"
    theme: [simple, lci.scss]
    echo: false
    transition: fade
    #output-file: lci_esot3_slides.html
    pdf-separate-fragments: true
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
---

## Cast

- Mary a young women who is about to deliver a baby
- Joseph - Her husband - faithful but a bit puzzled
- Innkeeper - Small business owner in Bethleham
- Chief Sheep - Extroverted leader sheep
- Under-sheep - Junior, but not used to following the crowd
- Angels - God's "shock and awe" messengers


## 

This is how the birth of Jesus came about:

Many years ago, God sent the angel Gabriel to a town called Nazareth to tell Mary something important.

At first Mary was troubled. But the angel said

>Do not be afraid, Mary.  God wants you to be the mother of his Son.

>You are to give him the name Jesus because he will save his people from their sins

Mary said she would do whatever God wanted.

Mary was very happy to become Jesus' mother

Now May was a virgin, promised to be married to a man named Joseph.

One day, Mary and Joseph had to take a trip.

They came to the town of Bethlemah. They looked for a place to sleep as she was expecting a child, but there were many people and there was no room for thim at the Inn.

Finally, the innkeeper said that they could stay in his stable with the animals.

Joseph made a soft bed for Mary. They lay down to sleep.

God’s son was born that night. 

**Mary wrapped him in soft cloths and laid him in a manger. She named her baby Jesus**

## Away in an Manger 
::: {style="font-size: 125%;"}
Away in a manger, no crib for a bed

The little Lord Jesus laid down His sweet head

The stars in the bright sky looked down where He lay

The little Lord Jesus asleep on the hay
:::

##

One the night Jesus was bor, some shephers were in the field taking care of their sheep. 

Suddenly, an angel appeared. The shepherds were afraid.

But the angel said  **Do not be afraid. A savior is born in Bethleham. You will find him wrapped in swaddling clothes and lying in a manger**

## First Noel 
::: {style="font-size: 125%;"}
The first Noel the angel did say 

was to certain poor shepherds in fields as they lay;

In fields where they lay tending their sheep,

On a cold win­ter’s night that was so deep.
\
\
Noel, Noel, Noel, Noel. 

Born is the King of Israel
:::

##

Suddenly thousands of ag=ngels appeared in the sky 

**They praise God for sending Jesus to be our savior, saying “Glory to God in the highest. And on earth peace, goodwill toward men.”**

## Hark the Herald Angels Sing

Hark! the herald angels sing, "Glory to the newborn King:

peace on earth, and mercy mild, God and sinners reconciled!"

Joyful, all ye nations, rise, join the triumph of the skies;

with th'angelic hosts proclaim, "Christ is born in Bethlehem!"
\
\
Hark! the herald angels sing, "Glory to the newborn King"


##

When the angels left, the shepherds ran to Bethlehem. *"Let's see if we can find this baby"* they said. 

When they found Jesus lying in a manger, they worshipped him. 

How excited they were!

**They told everyone the good news. They praised God all the way back to their fields**. 


## O Come All ye Faithful 

O come, all ye faithful, joyful and triumphant

O come ye, o come ye to Bethlehem

O come and behold Him, born the King of Angels

O come, let us adore Him x2

O come, let us adore Him, Christ the Lord
\
\

O come, all ye faithful x2

O come, all ye faithful to Bethlehem



## Coda

When Jesus was about 1 or 2 years old, some wise man followed a special star in the sky.

It led them to the house where the little boy Jesus liver. 

The Wwise men gave gifts to Jesus: gold, frankinsense, and myrrh.  They got down on their knees  and worshiped him. They knew he was to be a great king.

## We Three Kings of Orient Are


## God Rest Ye Merry Gentlemen


God rest ye merry gentlemen
Let nothing you dismay
Remember Christ our Savior
Was born on Christmas Day
To save us all from Satan's pow'r
When we were gone astray
Oh tidings of comfort and joy
Comfort and joy
Oh tidings of comfort and joy
God rest ye merry gentlemen
Let nothing you dismay
Remember Christ our Savior
Was born on Christmas Day
To save us all from Satan's pow'r
When we were gone astray
Oh tidings of comfort and joy
Comfort and joy
Oh tidings of comfort and joy
In Bethlehem, in Israel
This blessed Babe was born
And laid within a manger
Upon this blessed morn
The which His Mother Mary
Did nothing take in scorn
Oh tidings of comfort and joy
Comfort and joy
Oh tidings of comfort and joy
Fear not then, said the Angel
Let nothing you affright
This day is born a Savior
Of a pure Virgin bright
To free all those who trust in Him
From Satan's pow'r and might
Oh tidings of comfort and joy
Comfort and joy
Oh tidings of comfort and joy
God rest ye merry gentlemen
Let nothing you dismay
Remember Christ our Savior
Was born on Christmas Day
To save us all from Satan's pow'r
When we were gone astray
Oh tidings of comfort and joy
Comfort and joy
Oh tidings of comfort and joy

