---
title: "Eso Treatment Options"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient_education/)"
    css: ["lci_styles.css"]
    theme: default
    echo: false
    output-file: exo_rx_options_slides.html
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
---

I’m Dr Jonathan Salo, a GI Cancer Surgeon in Charlotte, North Carolina. If you or someone close to you has been diagnosed with esophageal cancer, this video is for you. In this video, you will learn about

-   How the cancer stage helps make treatment decisions
-   Four different treatment categories of esophageal cancer

------------------------------------------------------------------------

One of the challenges with communicating medical information by video is that not everyone' situation is the same. It goes without saying that the internet is no substitute for talking with your esophageal cancer care team. If you haven't already, you may want to watch our video about your cancer care team. I'll leave a link in the description below and the care above. [Your Esophageal Cancer Care Team](slides/03-Eso_Care_Team.html)

------------------------------------------------------------------------

# Deciding on Treatment

Several Factors go into making a decision about treatment for esophageal cancer:

-   Cancer Stage
-   Overall fitness of the patient
-   Patient preferences

------------------------------------------------------------------------

# Staging

The first task once we have a new diagnosis of cancer is staging. Staging is the process of finding out the extent of the cancer and whether or not it might have spread.

In some cases, there may be more than one treatment that is appropriate for the cancer stage, but the different treatments may be more or less rigorous. In these cases, the overall health of the patient will help find the best treatment.

------------------------------------------------------------------------

In other cases, there may be more than one treatment option and a patient's *preferences* in terms of the type of treatment become important.

All in all, the treatment decision requires a discussion between the patient and their care team to come up with the best plan. The purpose of these video is to provide you with *background information* and of course are no substitute for meeting with your treatment team.

------------------------------------------------------------------------

This video will cover all four treatment categories, which for many people allows them to get a broad overview, but for some it can be a bit overwhelming because there is a lot of information that *may not* apply to them.

Some of you will want more specific information that applies to your situation or that of a family member. I'll try to direct you to the right information.

------------------------------------------------------------------------

The first step in designing a treatment plan for esophageal cancer is staging. If you haven't seen it already, please see the video about esophageal cancer diagnosis and staging to give you an overview.

[Esophageal Cancer Diagnosis and Staging](02-Eso_Dx_Staging.html)

------------------------------------------------------------------------

# What if I don't know the stage?

If you haven't met with your treatment team to talk about the stage, I can give you some general direction to help get you started.

There is a lot of information on the internet about cancer, and it can be a bit overwhelming. With these videos we will try to help guide you to the information that's right for you.

We will talk about two general groups of patients, those with early stage disease, and those with advanced disease. Because esophageal cancer is difficult to detect early, advanced disease is very common.

------------------------------------------------------------------------

# Early vs Advanced Stage Disease

Patients with *Early Stage Disease* generally have T1 or T2 tumors and while they may have bleeding or reflux symptoms, they don't have difficulty eating or weight loss.

.pull-left\[

## Early Stage

-   T1 or T2 Tumors
-   No Difficulty Eating
-   Bleeding or reflux

\]

.pull-right\[

## Advanced Stage

-   Difficulty eating, especially solids
-   Weight loss frequent

\]

------------------------------------------------------------------------

Patients with *Advanced Disease* generally have T3 tumors and have some difficulty eating, and frequently have weight loss

.pull-left\[

## Early Stage

-   T1 or T2 Tumors
-   No Difficulty Eating
-   Bleeding or reflux

\]

.pull-right\[

## Advanced Stage

-   Difficulty eating, especially solids
-   Weight loss frequent

\]

------------------------------------------------------------------------

# Early Stage Disease

Patients with early stage disease can be divided into two categories:

-   I = Superficial -\> Treated without surgery
-   II = Localized -\> Treated with surgery alone

Superficial tumors are usually T1

## Localized tumors are T2 and some T1 tumors

# Advanced Stage Disease

Patients with early stage disease can be divided into two categories:

-   III = Locally Advanced -\> Preoperative therapy -\> Surgery
-   IV = Metastatic -\> Chemotherapy

Locally advanced tumors are usually T3

Metastatic tumors are usually M1 and have signs of spread to other organs

## We will have links at the end to videos about early stage or advanced stage disease.

# Category? Stage?

You'll notice I'm using the terms " Treatment Category I" rather than "Stage I". The reason is very simple. The cancer staging system was originally designed for researchers to predict outcomes after cancer treatment.

But for cancer patients and their families, what's important is what the best treatment is for their cancer. Unfortunately, the cancer stages don't exactly line up with how that cancer is treated.

------------------------------------------------------------------------

For instance, some Stage II patients are best treated with surgery while other Stage II patients are best treated with a combination of chemotherapy, radiation, and surgery.

The goal of these videos is to help patients understand *cancer treatment*.

Having said that, Stage 1 patients are *generally* treated with Treatment Category I, and the same with Stages 2, 3, and 4

------------------------------------------------------------------------

To review: Patients with early stage cancer usually don't have difficulty eating are more likely to have tumors that are superficial or localized, while patients with advanced disease tend to have trouble eating and weight loss are more likely to have tumors that are locally-advanced or metastatic.

------------------------------------------------------------------------

We hope you have found this video helpful. This videos and others like it are designed to educate patients and families about esophageal cancer and equip them for their discussions with their esophageal cancer care team.

As always, these videos are no substitute for expert medical advice.

------------------------------------------------------------------------

Feel free to subscribe so you can be notified about new videos. If you found this video helpful or if there are topics you would like us to cover, please let us know in the comments section.

Here are links to some videos that you may find helpful:

------------------------------------------------------------------------

# Links

[Advanced Esophageal Cancer](08-Eso_Advanced.html)

[Early Stage Esophageal Cancer](06-Eso_Early.html)

------------------------------------------------------------------------
