---
title: "Esophagectomy"
format: 
  docx:
    number-sections: true
    number-depth: 2
  html:
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true
    number-depth: 2
editor: visual
from: markdown+emoji
---

## Introduction. **L** **1**

I’m Dr Jonathan Salo, a GI Cancer Surgeon in Charlotte, North Carolina. These videos are designed to educate you about cancer and its treatment and help you and you cancer care team make the right decisions for you.

Of course, there is no substitute for the expert opinions of your cancer care team.

## Surgery of the Esophagus

In this viedo we'll discuss *surgery of the esophagus*

In this video, you will learn about (2)

-   Different Type of esophagectomy
-   Complications

At the end we will discuss ways that your surgical team can reduce the risk of complications

## Esophagectomy

Esophagectomy is the surgical removal of the esophagus

## Esophagectomy -

Another terms is esophagogastrectomy (4)

## Esophagectomy

Esophagectomy is generally performed for three different situations:

-   Superficial Tumors (T1) that can't be completely removed by endoscopy (5)

Superficial tumors are T1. If this terminology is not familiar to you, this may be a good time to view our video about Esophageal Cancer Staging and Treatment

We also have a separate video about superficial or "early stage" tumors and how they can sometimes be removed through endoscopic therapy without the need for surgery.

## Esophagectomy.

Esophagectomy is also performed for

-   Localized Tumors that are T1b or T2 (6)

## Esophagectomy

-   Locally Advanced Tumors, which are T3 or Node-positive (6)

## Esophagectomy

Locally-advanced tumors usually treated with some sort of preoperative therapy prior to surgery.  

Preoperative therapy is usually some combination of chemotherapy, immunotherapy or radiation therapy

We have videos which discuss locally-advanced esophageal cancer, which you may find helpful.

## Goals of Esophagectomy

The goals of esophagectomy are to remove the tumor (9)

## Goals of Esophagectomy

And nearby lymph nodes (10)

## Goals of Esophagectomy

An *additional* portion of the esophagus and stomach is also removed with the tumor to reduce the risk of recurrence (12)

## Reconstruction

In most cases, the lower part of the stomach is fashioned into a tube, to create a new esophagus.
## Reconstruction

The esophagus and stomach tube are now joined together

The new connection between esophagus and stomach is called the anastomosis (14)

## Types of Esophagectomy. **4**

There are two major types of esophagectomy:


Partial esophagectomy removes the lower 2/3 of the esophagus

Total esophagectomy removes all of the esophagus (15)

## Partial Esophagectomy **2**

During a partial esophectomy, the new connection between esophagus and stomach  (or anastomosis) made in the chest (16)

## Ivor Lewis Esophagectomy

A partial esophagectomy is also referred to as an Ivor Lewis esophagectomy

## Total Esophagectomy

A total esophagectomy removes all of esophagus, and a new connection (or anastomosis) made in the neck (18)

## Total Esophagectomy

Two different approaches to total esophagectomy

Transhiatal approach or

McKeown which is also known as the three-incision esophagectomy (19)

## Which Esophagectomy? **4**

Your surgeon will recommend a surgical approach based upon a number of factors.

One factor is the location of the tumor (20)

## Distal - Partial **2**

For tumors located in the lower, or distal part of the esophagus, a Partial esophagectomy will remove the cancer and enough additional esophagus to ensure that the cancer is completely removed (21)

## Distal - Partial

So for distal cancers, an Ivor Lewis Approach is a common operation (22)

## Upper = Proximal

For tumors located in the upper or proximal part of the esophagus, a total esophagectomy is required to remove all of the cancer.

## Which Esophagectomy - Suirgeon **4**

Another important factor is surgeon preference and experience.

You will have an opportunity to discuss the operation when you meet with your surgeon


## Why Remove so much Esophagus?

A question I am commonly asked is "why do you need to remove so much esophagus?="


## Esophagectomy

On the left is a diagram of a standard Ivor Lewis esophagectomy.

On the right is a proximal gastrectomy. The operations are different because much *less* esophagus is removed with a proximal gastrectomy. 

With a proximal gastrectomy, the anastomosis is much lower in the chest cavity.


## Ivor Lewis Esophagectomy vs Proximal

The Ivor Lewis approach removes *more* esophagus and the proximal gastrectomy removes *less*

On the right is a proximal gastrectomy. The operations are different because much *less* esophagus is removed with a proximal gastrectomy. 

With a proximal gastrectomy, the anastomosis is much lower in the chest cavity.

## Ivor Lewis Esophagectomy vs Proximal

As it turns out, there is *more* acid reflux with a proximal gastrectomy.

## Ivor Lewis Esophagectomy vs Proximal

We have found that the quality of life is better if about half to two-thirds of the esophagus is removed, with the result that the anastomosis is a bit higher in the chest.

## Surgical Techniques **2**

Another aspect of surgery are the techniques used.

An esophagectomy can be performed with open techniques

or minimally-invasive techniques (25)

## Open Surgery

An open esophagectomy uses a laparotomy incision to access the abdomen, and a thoracotomy to access the chest (26)

## Minimally InVasive

Minimally-invasive technique uses small incisions and specialized instruments.(27)

## Minimally InVasive


These techniques can reduce discomfor and length of hospital stay. (28)

## Laparoscoic techniques

Laparoscopic techniques use special instruments to work through small incisions. These are directly controlled by the surgeon. (28)

## Robotic techniques

In some cases, robotic techniques can be used. The surgeon controls the robotic instruments from a console (29) which allows 3-D view inside the abdominal cavity


## Robotic techniques

The surgeon operates the hand controls (30) 



## Robotic techniques

...and is able to direct the movements of the robotic arms (31) 



## Robotic techniques

The robot arms are attached to instruments which which enter the abdomen through small incisions (32) 


## Robotic techniques

The robot precisely mimics the actions of the surgeon (33)

If you search on the internet for "surgical robot grape" you can see the robot in action as it is used to suture the skin back on a grape.  

You will get a feel for the precision of a surgical robot. 



## Risks of Surgery **4**

There are complications of surgery you will want to discuss with your surgeon

-   Leakage from the anastomosis
-   Pneumonia

## Leak from Anastomosis **2**

The anastomosis is the new connection made between the esophagus and the stomach.

If the anastomosis does not heal properly. (34)

## Leak from Anastomosis

There will be leakage of fluid from inside the esophagus into the chest cavity. (3=5)

## Leak from Anastomosis

This can lead to infection (36)

## Leak from Anastomosis

and a prolonged hospital stay (37)

## Treatment of Leak

In some cases, small leaks will heal as long as there is adequate nutrition (38)

## Stent

IN other  cases a stent is placed inside the esophagus to patch the leak from the insisde (40)

## Esophageal Stent

The stent is a wire mesh tube covered in plastic, which is placed inside the esophagus by endoscopy. (41)

## Esophageal Stent

Once healing has occured, the stent is removed, typically about 6 weeks later (42)


## Pneumonia **2**

Pneumonia is an infection in the lungs(48)

which come from bacteria in the mouth



## Secretions from the Mouth

The secretions in the mouth contain bacteria (50)

and ordinarily these secretions pass into the esopahogus

and are swallowed



## Secretions from the Mouth

Those secretions *can* occasionally enter the windpipe (53)

## Secretions from the Mouth

But are ordinarily quickly cleared by a cough (54)

## Secretions in the Airway

After surgery... particularly after patients have been asleep for a period of time

Secretions in the airway more easily pass into the lungs

...and can cause pneumonia




## Pneumonia Prevention after Surgery

Pneumonia prevention after surgery means clearing secretions from the lungs by Coughing (61)


## Pneumonia Prevention after Surgery

Deep breating (62)


## Pneumonia Prevention after Surgery

and Walking (63)

## INcentive spirometer

An incentive spirometer is a device which can help coach you to take deep breaths after surgery (64)


## Pain control

Coughing, deep breating, and walking after surgery can be unconfortable, 

so another important strategy to prevent pneumonia is to work to minimize discomfort. (67)


## Pain control

Minimally-ilnvasive techniques, either laparoscopic or robotic, can help reduce discomfort by the use of small incisions (66)


## Pain control

The other strategy is pain control


## Epidural Catheter

An epidural catheter can help with postoperative pain control. 

This is similar to the epidural used for childbirth. 

A small tube is placed under the skin near the spine with local anesthetic  (68)


## Epidural Catheter

This allows the administration of pain medicines whcih can provide pain relief without sedation 69)

This makes it easier to walk without discomfort.



## Epidural Catheter

The goal is to minimize pain (70)

And make it easier to cough, deep breathe, and walk after surgery

## **1**

We hope you have found this video helpful. Here are links to some other videos.

Feel free to leave a comment or a question, or if you have suggestions for future videos.

If you or a family member have had an encounter with esophagectomy surgery, I would love to hear about your experience, so please take a minute to leave a comment below.

We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.  (29)

