---
title: "Barrett's Esophagus"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient _education/)"
    #css: ["theme/theme.css"]
    css: ["lci_styles.css"]
    theme: default
    echo: false
    output-file: eso_barrets_slides.html
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
---

I’m Dr Jonathan Salo, a GI Cancer Surgeon in Charlotte, North Carolina. If you or someone close to you has been diagnosed with esophageal cancer, this video is for you. In this video, you will learn about *Early Stage* esophageal cancer

------------------------------------------------------------------------

For a refresher, esophageal cancer, as it grows, can tends to make it difficult for patients to swallow.

So patients with esophageal cancer fit into two main groups:

-   A small group who don't have any difficulty eating that have *early* stage disease
-   Majority of patients who have some difficulty eating or may have weight loss who have *advanced* disease.

--

Among those with *Advanced* disease, there are two categories:

-   Locally Advanced -\> T3 or N+ -\> Treated with a combination of chemotherapy + radiation, followed by surgery
-   Metastatic -\> Treated with chemotherapy

For more information about *advanced* esophageal cancer, there is a link above and in the description. [Advanced](08-Eso_Advanced.html)

------------------------------------------------------------------------

In this video, you will learn about *Early Stage* esophageal tumors. These generally don't cause any difficulty with eating or swallowing. They may cause bleeding or symptoms of heartburn, but generally don't cause trouble eating or weight loss.

Early Stage cancers are those that are T1 or T2 and N0M0.

If you haven't seen it already, please see the video about esophageal cancer diagnosis and staging to give you an overview.

[Esophageal Cancer Diagnosis and Staging](02_Eso_Dx_Staging.html)

------------------------------------------------------------------------

In short, early stage cancers consist of small tumors without involvement of the lymph nodes, and they are either T1 or T2.

T1 tumors are treated very differently from T2 tumors, to it is important to distinguish between the two.

------------------------------------------------------------------------

**Endoscopic ultrasound** is the best test to distinguish T1 tumors from T2 tumors. From a patient's perspective it's very similar to an upper endoscopy. Under sedation, the gastroenterologist places a scope through the mouth into the esophagus. The difference is that at the end of the scope, there is located a tiny ultrasound probe, which can measure the tumor in the esophagus.

------------------------------------------------------------------------

The endoscopic ultrasound will give one of three answers:

T1 tumor -\> can frequently be treated through the endoscope, without the need for surgery. We'll discuss that more later

T2 -\> Are usually treated with surgery

T3 -\> Treated with a combination of chemotherapy

------------------------------------------------------------------------

# T1 Esophageal Cancers

T1 tumors involve only the mucosa, the layer on the inner surface of the esophagus. Because these tumors do not invade deeply, it is often possible to remove them using a scope. In some cases, the tumor can be treated without the need for surgery. Endoscopic removal of tumor is called *endoscopic mucosal resection*

------------------------------------------------------------------------

# Endoscopic Musocal Resection

For the patient's perspective, the procedure is similar to an endoscopy, which is done under sedation. Fluid is injected underneath the tumor, which raises a sort of blister. The top layer (and the tumor) are then removed. The procedure is done as an outpatient.

------------------------------------------------------------------------

# Pathology

The pathologist then examines the specimen to see whether the tumor has been removed completely

------------------------------------------------------------------------

(favorable) In an ideal circumstance, the tumor is confined to the center of the area which has been removed, ensuring that there is no tumor left behind.

A tumor is judged to be *favorable* for endoscopic mucosal resection if the tumor appears to be slow growing and the margins are clear, which suggests that the tumor was completely removed.

------------------------------------------------------------------------

# Surveillance

When a small tumor has been completely removed by endoscopic mucosal resection, frequently no further therapy is required. In this case, follow up endoscopy is recommended to be certain that there is no recurrence.

------------------------------------------------------------------------

**Unfavorable**: If a tumor is removed with endoscopic mucosal resection and it appears as though the tumor may not have been completely removed *or* is more rapidly growing, this is considered an *unfavorable* outcome. In this care there are two options:

1.  surgical removal with esophagectomy or
2.  close surveillance with endoscopy.

------------------------------------------------------------------------

We hope you have found this video helpful. This videos and others like it are designed to

educate patients and families about esophageal cancer

and equip them for their discussions with their esophageal cancer care team.

As always, these videos are no substitute for expert medical advice.

------------------------------------------------------------------------

If you or a family member have had an encounter with esophageal cancer surgery, I would love to hear about your experience, so please take a minute to leave a comment below. We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.

------------------------------------------------------------------------

In the next video in our series you will learn about surgery for esophageal cancer. Surgery is usually recommended for patients with T1 tumors which can't be removed by endoscopic therapy and for patients with T2 tumors.

[Surgery for Esophageal Cancer](12-Eso_surgery.pdf)

To learn about *advanced* esophageal cancer, which generally causes difficulty eating, we have a video with the link below: [Advanced](08-Eso_Advanced.html)

------------------------------------------------------------------------
