---
title: "Central Venous Port"
format: 
  docx:
    number-sections: true
    number-depth: 2
  html:
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true
    number-depth: 2
editor: visual
from: markdown+emoji
---

## Intro L *1*

I'm Dr Jonathan Salo, a GI Cancer Surgeon at the in Charlotte, North Carolina If you’re seeing this video, changes are you or someone close to you has had an encounter with cancer. These videos are designed to educate you about cancer and its treatment and help you and you cancer care team make the right decisions for you.

Of course, there is no substitute for the expert opinions of your cancer care team.

## Intravenous Drug Administration *L* *4*.

The topic of this video is methods for the intravenous administration of drugs

Most of the drugs used to treat cancer need to be administered in the veins(2)

There are three different methods which can be used to administer drugs intravenously:

## Intravenous Drug Administration 

## Treatment is guided by the Stage of cancer. 2

The treatment recommended will depend upon the stage of the cancer. If you haven't already, this may be a good time to view the video on Diagnosis and Staging.

## Staging

A PET or CT scan is used for staging. If the scans show that the tumor is localized, without signs of spread beyond the nearby lymph nodes, it is considered M0.

On the other hand, if the scans show signs of spread, this is considered Metastatic Disease or M1. (4)

## Metastatic Disease = M1

Patients with metastatic disease are best treated with chemotherapy and are generally not treated with surgery. (5)

## Locally Advanced Esophageal Cancer *4*

We will focus in this video on Locally-advanced cancers

## Locally-advanced Esophageal Cancer T2/3 or N+.

Locally advanced esophageal cancer has not spread to other organs in the body. Locally-advanced cancers are not only M0, but they are either T2 or T3 or node-positive. (7)

If this terminology is not familiar to you, please refer to our video on Diagnosis and Staging. There is a link above and in the description below.

## Locally-advanced: M0

Locally-advanced cancers are M0, which means there is no evidence of metastasis, or spread to other parts of the body. (8)

## Adenocarcinoma vs Squamous Cell.

To make things a bit more complicated, there are two types of esophageal cancer: Adenocarcinoma and Squamous Cell Carcinoma. The treatment of there cancers is somewhat similar, but different enough that we have prepared a video to specifically address squamous cell carcinoma. (9)

## Types of Esophageal Cancer

This video will focus on locally-advanced squamous cell carcinoma (10)

## Why not just Cut it out?

I am occasionally asked by patients why we don't just remove esophageal cancer with surgery as the first treatment. (11)

The answer is a bit complex.

## <Esophageal cancer graphic>

When a patient is diagnosed with cancer of the esophagus or gastroesophageal junction, it can look like the cancer is confimed to the esophagus. (12)

## \<esophageal cancer with 'fingers'\>

what we see from inside the esophagus is just the tip of the iceberg.

There is frequently spread of cancer cells into the nearby tissue or lymph nodes (13)

## <surgery without preop>

If surgery is performed as the only therapy for locally-advanced cancer, (14)

## <postop without preop>

there is a risk that cancer cells can be left behind (15)

## Locally Advanced

Preoperative therapy is administered before surgery And is designed to shrink the tumor (16)

## Locally Advanced

and kill cancer cells in the surrounding area

This therapy typically involves chemotherapy (17)

## Locally Advanced

and may involve radiation (18)

## Locally Advanced

The overall goal is shrinking the tumor and killing nearby cancer cells, to make the surgery more effective (19)

## Surgery

After preoperative therapy has shrunk the tumor and any other cancer cells, surgery can be performed

## Post Surgery

Preoperative therapy combined with surgery offers the best chance to remove all of the cancer, without leaving any behind (21)

## Post Surgery and Reconstruction

...without leaving any cancer cells behind (22)

## Preoperative Therapy *4*

-   Shrinks the tumor
-   Make surgery more effective
-   Leads to better cancer control than surgery alone (23)

## Neoadjuvant

You may hear preoperative therapy referred to as "neoadjuvant therapy" (24)

## Preop Therapy

For squamous cell carcinoma, chemotherapy and radiation are delivered at the same time before surgery (25)

## Chemotherapy + Radiation -\> Surgery

The chemotherapy and radiation strategy uses chemotherapy and radiation together

Chemotherapy is given intraveneously once per week

Radiation is given five days per week

Both are administered together for 5 1/2 weeks

This is also know as the "CROSS" treatment regimen (26)

## Chemotherapy + Radiation -\> Surgery

The chemotherapy is a low dose, designed to make the radiation more effective

The therapy is generally well tolerated

Hair loss is uncommon

Low blood counts are also uncommon, and occur in about 7% of cases

## Radiation Esophagitis

The radiation can, however, cause inflammation in the esophagus called esophigitis.

This can make eating more uncomfortable during the last two weeks of radiation (28)

## Radiation Esophagitis

The good news is that this is temporarily and usually resolves within 2 or 3 weeks after the radiation is completed. (29)

## Radiation Esophagitis

What this may mean, however, is placement of a temporary feedindg tube may be needed. (30)

## Radiation Esophagitis

The feeding tube can usually be removed 2-3 weeks after the end of radiation, as the cancer shrinks and the inflammation subsides (31)

## Chemo + Radiation -\> Surgery *2*

To summarize, This approach to preoperative therapy uses six weeks of chemotherapy and radiation together.

Surgery is typically performed 6-8 weeks after the end of radiation, as soon as patients have recovered. (32)

## Chemo + Radiation -\> Surgery

After surgery, the pathologist examines the cancer that has been removed.

One of the things the pathologist looks for is how well the preoperative chemotherapy and radiation killed the cancer before the surgery

In some cases, the pathologist doesn't find any cancer that looks alive. (33)

## Chemo + Radiation -\> Surgery

After surgery, the pathologist examines the cancer that has been removed.

One of the things the pathologist looks for is how well the preoperative chemotherapy and radiation killed the cancer before the surgery

In some cases, the pathologist doesn't find any cancer that looks alive. (34)

## Chemo + Radiation -\> Surgery

In about half the cases of patients treated with chemotherapy and radiation, followed by surgery, the pathologist does not find any evidence of live cancer cells in the specimen (35)

## Chemo + Radiation -\> Surgery

In these cases, the cancer was probably cured by the chemotherapy + radiation alone (36)

## Chemo + Radiation

Patients with squamous cell carcinoma of the esophagus are *cured* by chemotherapy and radiation *alone* in about half of cases. (37)

## Chemo + Radiation

It can be hard to know for certain who is cured immediately after the chemotherapy and radiation are finished (38)

## Chemo + Radiation

The decision-making about what to do after chemotherapy and radiation is made more complicated by the fact that it's hard to know for certain who is cured immediately after chemotherapy and radiation is finished. (39)

## Chemo + Radiation -\> Surveillance

The first step is to repeat the upper endoscopy (or EGD) and the scans after the completion of chemotherapy and radiation to look for evidence of persistent cancer what wasn't killed by the therapy (40)

## Chemo + Radiation -\> Surveillance

These tests will result in one of two answers: Either there is no visible cancer found, or persistent cancer is found by either endoscopy (EGD) or on scans (41)

## Chemo + Radiation -\> Surveillance

In most cases, about 80%, no visible cancer is found, and in 20%, there is evidence of persistent cancer. (42)

## Chemo + Radiation -\> Surveillance

Patients with persistent disease after chemotherapy and radiation are often candidates for surgery (43)

## Chemo + Radiation -\> Surveillance

Among patients with no evidence of cancer after chemotherapy and radiation, some are cured, but some simply have *hidden cancer* which will eventually grow back over time (44)

## Chemo + Radiation -\> Surveillance

Those patients who initially have no visible cancer, in whom the cancer later regrows, are candidates for surgery. (45)

## Active Surveillance

So how can we figure out which patients without visible cancer have hidden cancer that might regrow in time?

The strategy is call Active Surveillance. (46)

## Chemo + Radiation -\> Surveillance

So how can we figure out which patients without visible cancer have hidden cancer that might regrow in time?

The strategy is call Active Surveillance. (46)

## Active Surveillance

Patients who have no visible cancer after chemotherapy and radiation have an endoscopy every 3 to 4 months for the next 2 years (47)

## Active Surveillance

As long as no evidence of recurrence is found (48)

## Active Surveillance

If recurrent cancer is found, surgery can be done at that point (49)

## Preparing for Preoperative Therapy-2

I know this all sounds rather complex, but the starting point is to get prepared for chemotherapy and radiation.

There are three important ways:

First is to make sure you take in enough protein in your diet. We have a video on nutrition.

Second is to stay active. We recommend 30minutes each day of vigorous exercise such as brisk walking

Third is to be careful about your dental hygeine. If you need any dental work done, check with your dentist. Keeping your teeth healthy can reduce the risk of infection during therapy. (50)

## Preparing for Preoperative Therapy-2

In some cases, a feeding tube may be be necessary in order to maintain adequate nutrition.

A central venous port may be needed to help wlith the admnistration of chemotheray. (51)

## Wrap up *1*

We hope you have found this video helpful. Here are some other topics for which videos have been posted or are planned.

Feel free to leave a comment or a question, or if you have suggestions for future videos.

If you or a family member have had an encounter with esophageal cancer, I would love to hear about your experience, so please take a minute to leave a comment below.

We're constantly creating new videos, so please subscribe to be notified of new videos when we post them. (51)
