---
title: "Esophagus Early Stage"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient _education/)"
    #css: ["theme/theme.css"]
    css: ["lci_styles.css"]
    theme: default
    echo: false
    output-file: eso_early_slides.html
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
---

# Introduction

I’m Dr Jonathan Salo, a GI Cancer Surgeon at the Levine Cancer Institute in Charlotte, North Carolina.

If you're viewing this video, chances are that you or someone close to you has encountered esophageal cancer and is contemplating treatment.

------------------------------------------------------------------------

For a refresher, esophageal cancer, as it grows, can tends to make it difficult for patients to swallow.

So patients with esophageal cancer fit into two main groups:

-   A small group who don't have any difficulty eating that have *early* stage disease
-   Majority of patients who have some difficulty eating or may have weight loss who have *advanced* disease.

------------------------------------------------------------------------

Patient with *advanced* esophageal cancer fit into two categories: Locally Advanced and Metastatic. Patients with advanced esophageal cancer usually have some difficulty eating, so nutrition becomes an important part of the treatment plan. We have a video on nutrition **Link card**

-   Locally Advanced -\> T3M0
-   Metastatic -\> M1

For more information about advanced esophageal cancer, there is a link above and in the description. [Advanced Esophageal Cancer](eso_advanced.html)

------------------------------------------------------------------------

Among those with early stage disease, there are two categories:

-   Superficial -\> Treated without surgery
-   Localized -\> Treated with surgery alone

------------------------------------------------------------------------

If this terminology is not familiar to you, please refer to our video on Gastroesopahgeal Cancer Diagnosis and Staging. There is a link above and in the description below.

[Esophageal Cancer Diagnosis and Staging](ge_dx_staging.qmd)

------------------------------------------------------------------------

::: columns
::: {.column .fragment width="50%"}
Early Esopageal cancers are T1 or T2, and have no evidence of spread to the lymph nodes AND there is no sign of metastatic disease.  They are therefore T1 N0 M0 or T2 N0 M0
:::

::: {.column .fragment width="50%"}
!!! Need graphic with T1 AND T2 tumors !!!
:::
:::

## Detection

Patients with early stage esophageal cancer usually don't have any difficulty swallowing.  Instead, most patients discover they have an early-stage cancer when they have reflux symptoms or bleeding from the gastrointestinal tract.  This leads to an upper endoscopy and a diagnosis.

## Barrett's esophagus

For many patients, early stage esophageal cancer is a result of long-standing reflux, which causes Barrett's esophagus.

In ordinary circumstances, food passes from the throat to the esophagus to the stomach. Acid in the stomach then starts the process of digesting food. A one-way muscular valve called the sphincter keeps acid in the stomach and prevents it from refluxing up into the esophagus.

In some cases, however, the sphincter doesn't work properly and acid can splash up into the esophagus, which can cause symptoms of heartburn. In addition, the acid causes irritation to the lining of the esophagus called the mucosa.  Over time, in response to the irritation, the esophagus changes the lining and it becomes more resistant to acid. In many cases, the symptoms go away but the acid reflux persists. The new lining that forms on the mucosa of the lower esophagus is called Barrett's Esophagus


## Dysplasia

Over time, the cells that make up Barrett's Esophagus can begin to change and become more abnormal-looking under the microscope. This is termed *dysplasia*, and is important because dysplasia can in some cases lead to cancer.

## Esophageal cancer

With the passage of time, the Barrett's Esophagus cells can acquire the ability to grow and ignore the normal signals that keep cells from growing.  At this point, the cells have the ability to grow, and are called cancer or carcinoma cells.

## 

At first, the cells are confined to the top layer called the mucosa. These are termed intramucosal cancers, or T1. The good news is that if they are detected early, they can often removed with endoscopy and don't require surgery.

## EMR

One technique which can allow the removal of a T1 cancer by endoscopy is called endoscopic mucosal resection.  In this technique, a small amount of fluid is injected underneath the top layer, raising a sort of blister.  This can then allow the tumor and a surrounding disk of tissue.  The pathologist then examines the tissue to see whether all of the cancer cells have been removed.

## Favorable

The ideal situation is one in which the cancer cells are located in the middle of the tissue removed, a little like a sunny-side up fried egg. This is considered a "favorable" situation and in many cases patients need no further therapy, but just need careful follow up with with periodic upper endoscopy or EGD

## Unfavorable

In cases, the cancer cells are found at the edge or the bottom of the tissue removed, and this raises questions about whether there might be cancer cells left behind. This is considered and "unfavorable" situation.  In some cases, the best approach is surgery, especially if there are cancer cells found at the bottom of the tissue removed. In other cases, careful follow up endoscopy is performed.

## T2

In some cases, an esophageal cancer is not discovered until it grows much deeper into the wall.  Once it grows into the muscle, it is too deep to remove with the endoscope and surgery is required.

In most cases, an endoscopic ultrasound is needed to confirm the precise depth of the cancer.  

We have a video on esophageal cancer surgery here [Esophagectomy](eso_surgery.html)

If it grows all the way through the muscular wall, it is considered T3 and *Locally Advanced*.  In these cases, it is best to becgin with chemotherapy and/or radiation therapy in order to shrink the tumor prior to surgery.

---

I hope you have found this video helpful. This videos and others like it are designed to educate patients and families about esophageal cancer and equip them for their discussions with their esophageal cancer care team.

As always, these videos are no substitute for expert medical advice.

------------------------------------------------------------------------

Feel free to leave a comment or a question, or if you have suggestions for future videos.

If you or a family member have had an encounter with esophageal cancer, I would love to hear about your experience, so please take a minute to leave a comment below.

We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.

------------------------------------------------------------------------

Here are some additional videos you may find helpful:

[Esophagectomy](eso_surgery.html)
[Locally Advanced Esophageal Cancer](eso_aca_locally_advanced.html) 

------------------------------------------------------------------------
