---
title: "Locally-Advanced Adenocarcinoma"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient _education/)"
    #css: ["theme/theme.css"]
    css: ["lci_styles.css"]
    theme: default
    echo: false
    output-file: eso_advanced_slides.html
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
---

## 1 Intro

I'm Dr Jonathan Salo, a GI Cancer Surgeon at the in Charlotte, North Carolina
If you’re seeing this video, changes are you or someone close to you has had an encounter with esophageal cancer.
These videos are designed to educate you about cancer and its treatment and help you and you cancer care team make the right decisions for you.

Of course, there is no substitute for the expert opinions of your cancer care team.


## 4 Esophageal Cancer (2)

For a refresher, esophageal cancer, as it grows, can tends to make it difficult for patients to swallow.

So patients with esophageal cancer fit into two main groups:

-   A small group who don't have any difficulty eating that have *early* stage disease
-   Majority of patients who have some difficulty eating or may have weight loss who have *advanced* disease.

## Esophageal Cancer (3)

This video will focus on Advanced Stage Disease

We will post videos about early stage disease, so take a look in the description.


## Advanced Stage Cancer (4)

 *Advanced* esophageal cancer consists of two categories: Locally Advanced and Metastatic.

-   Locally Advanced -\> T3M0
-   Metastatic -\> M1


## 2 Metastatic Cancer:M1 (5)

Metastatic cancers are those that have signs of spread to other organs such as the lungs, liver, or bones.

These cancers are treated primarily with chemotherapy.

We have other videos that focus on metastatic cancers.

## Locally-advanced: M0 (6)

Locally-advanced cancers are M0, which means there is no evidence of metastasis, or spread to other parts of the body.  In addition, they are T3 or node-positive

## Locally-advanced: T3 or N+ (7)

Locally-advanced cancers are not only M0, but they are T3 or node-positive.

If this terminology is not familiar to you, please refer to our video on Diagnosis and Staging. There is a link above and in the description below.

## 4 Types of Esophageal Cancer (8)

To make things a bit more complicated, there are two types of esophageal cancer: Adenocarcinoma and Squamous Cell Carcinoma.

The treatment is in many ways similar, but there are enough differences that we will have a separate video that focuses on squamous cell carcinoma. 

## Types of Esophageal Cancer (9)

This video will focus on locally-advanced *adenocarcinoma*


## (6) Locally Advanced (10)

Locally-advanced cancers frequently have localized spread of cancer cells outside of the visible tumor.

##  Locally Advanced (11)

Surgery removed the visible tumor and the surrounding tissue, but does not always remove microscopic spread of cancer which can't be seen with the naked eye.

##  Locally Advanced (12)

If surgery is performed as the only therapy for locally-advanced cancer, there is a risk that cancer cells can be left behind

##  Locally Advanced (13)

Preoperative therapy is administered before surgery

##  Locally Advanced (14)

And is designed to kill cancer cells in the tumor, nodes, and any cancer cells in the surrounding area

##  Locally Advanced (15)

This therapy typically involves chemotherapy

##  Locally Advanced (16)

Which can circulate all throughout the body

##  Locally Advanced (17)

Chemotherapy can be combined with radiation in some cases

##  Locally Advanced (18)

The overall goal is shrinking the tumor and killing nearby cancer cells


##  Locally Advanced (19)

After preoperative therapy has shrunk the tumor and any other cancer cells, surgery can be performed

##  Locally Advanced (20)

Preoperative therapy combined with surgery offers the best chance to remove all of the cancer, without leaving any behind

## (4) Squamous Cell Preoperative Therapy (21)

The good news is that squamous cell carcinoma is very sensitive to a combination of radiation and chemotherapy.

##  Chemotherapy + Radiation -> Surgery (22)

Chemotherapy is given intraveneously once per week for 6 weeks

Radiation is given five days per week for 6 weeks

##  Chemotherapy + Radiation -> Surgery (23)

The chemotherapy is a low dose, designed to make the radiation more effective

The therapy is generally well tolerated

## (2) CROSS Clinical Trial (24)

The effectiveness of this approach was proven scientifically in the CROSS clinical trial

This was a scientific study published in 2010

363 patients with locally-advanced esophageal cancer were divided into two treatment groups:

One group was treated with surgery alone

The other group was treated with chemotherapy and radiation first, followed by surgery

##  CROSS Clinical Trial (25)

The results of the trial were quite dramatic: There was better control of the cancer in the group that received chemotherapy and radiation prior to surgery. This group had longer survival than the group treated with surgery alone.

##  CROSS Clinical Trial (26)

For the past 15 years, chemotherapy and radiation, followed by surgery, was established as the most effective therapy. This is known as trimodality therapy, because it uses a combination of three different therapies.


## (2) Preoperative Therapy (27)

The radiation will work to kill cancer cells, but it can also damage the healthy tissue in your body as well, particularly the lining of the esophagus.

This irritation to the lining of the esophagus is called *radiation esophagitis* and can be thought of as a "sunburn" on the inside of the esophagus.

Radiation esophagitis is usually at it worst during the last two weeks radiation, and can make swallowing worse.

Within two weeks after radiation is completed, swallowing is starting to get better as the tumor in the esophagus shrinks.

For this reason, a temporary feeding tube is frequently necessary for patients getting chemotherapy and radiation.  We have a video that discusses nutrition and feeding tubes.


##  Preoperative Therapy (28)

Within two weeks after radiation is completed, swallowing is starting to get better as the tumor in the esophagus shrinks.

For this reason, a temporary feeding tube is frequently necessary for patients getting chemotherapy and radiation.  We have a video that discusses nutrition and feeding tubes.

##  Preoperative Therapy (29)

For this reason, a temporary feeding tube is frequently necessary for patients getting chemotherapy and radiation.  A feeding tube is usually placed before chemotherapy and radiation starts, and can often be removed 2 to 3 weeks after radiation is completed

We have a video that discusses nutrition and feeding tubes.


## After Chemotherapy + Radiation (30)

After chemotherapy and radiation are completed, your care team will develop a plan to evaluate the effectiveness of the treatment.  This may include:

- PET scan 4-6 weeks after the end of radiation

## After Chemotherapy + Radiation (31)

and upper endoscopy or EGD


## Surgergy after Chemotherapy + Radiation (32)

The decision-making regarding surgery after chemotherapy and radiation for esophageal *squamous cell carcinoma* is complex.  You will have an opportunity to meet with your esophageal cancer care team after the chemotherapy and radiation are completed.

## Surgergy after Chemotherapy + Radiation. (33)

The good news is that squamous cell carcinoma of the esophagus, unlike the other kind of esophageal cancer called adenocarcinoma, is very sensitive to chemotherapy and radiation.

In fact, it is estimated that 40% of patients with squamous cell carcinoma of the esophagus are cured by chemotherapy and radiation alone. 


## Surgergy after Chemotherapy + Radiation. (33)

The challenge is that it can be difficult to identify the 40% that are cured vs the 60% who have persistent cancer after chemotherapy and radiation.  

## Treatment after Chemotherapy + Radiation (33)

There are several possible options after the completion of chemotherapy and radiation for squamous cell carcinoma.

- Surgery
- Systemic therapy
- Active Surveillance




##  Additional Topics (35)


We hope you have found this video helpful. Here are some other topics for which videos have been posted or are planned.

Feel free to leave a comment or a question, or if you have suggestions for future videos.

If you or a family member have had an encounter with esophageal cancer, I would love to hear about your experience, so please take a minute to leave a comment below.

We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.
