---
title: "Central Venous Port"
format: 
  docx:
    number-sections: true
    number-depth: 2
  html:
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true
    number-depth: 2
editor: visual
from: markdown+emoji
---

## Introduction. *1*

Cancers or all kinds are frequently treated with chemotherapy or immunotherapy drugs which need to be administered through the veins.

I’m Dr Jonathan Salo, I’m a GI Cancer Surgeon.

In this video you’ll learn about the different methods of intravenous drug administration

## Types. L *4*

There are three options for intravenous administration of drugs:

- Peripheral Intravenous line (which is likely familiar to most people)
- PICC Line or Peripherally Inserted Central Catheter
- Central Venous Port (commonly referred to as a Port-a-Cath)

## Peripheral IV *2*

A peripheral IV is placed through the skin into a vein in the hand or forearm.

The catheter is removed the same day and then replaced when it's time for the next dose, which is typically one to three weeks later.

For patients who receive FLOT chemotherapy, a peripheral IV is not suitable because this treatment requires a 24-hour infusion of drug.

## PICC LIne

A PICC line is a special intravenous line with a long tube that brings drugs to the veins near the heart.

This catheter can be left in place for several weeks.

It is suitable for FLOT chemotherapy

The disadvantage of the PICC line is that that dressing needs to be kept dry as long as the catheter is in place.

## Central Venous Port

A Central Venous Port is a small device which is surgically placed underneath the skin.  

It contains a small chamber with a flexible rubber top and a tube that goes into the veins near the heart

When it comes time to administer drugs, a needle is passed through the skin into the chamber

This avoids having to find a vein underneath the skin in the arm or hand. The port is ideal for those with small veins which might be difficult to access with a peripheral intravenous line

## Central venous Port (no veins)

The port is completely implanted, so patients can shower, bathe, and swim with the device in place


## Central Venous Port (vein diagram)

The catheter attached to the chamber delivers drugs into the main vein near the heart

The central venous port is suitable for FLOT chemotherapy

## Port Access

When it comes time to administer the drug, the skin is numbed with a medicated cream, and a needle is inserted into the port.  

Once the drug has been delivered, the needle is removed.

## Central Venous Port (9)

A central venous port can be placed by a radiologist or surgeon

Port placement can be combined with other procedures such as diagnostic laparoscopy or feeding tube placement

## Central Venous Port Insertion (10)

Typically, the port is placed in the operating room under sterile conditions. A 1 inch incision made below the collar bone, and frequently a smaller incision is made in the neck. The procedure is done an an outpatient, so you can go home the same day.

The care of a port after surgery is very easy, as there are no tubes outside the body to worry about.

The sutures are all under the skin and will dissolve on their own. The incision should be dry for at least 24 hours. We recommend no heavy lifting for the first week to avoid bruising.

Typially, the incisions will be covered with a surgical glue which will flake off after a week or so.

## Summary *4*

In summary, we have 3 options for intravenous access to administer chemotherapy or immunotherapy:

- Periperheral Intravenous Line
- PICC LIne
- Central venous Port

## Outro *1*

We hope you have found this video helpful.  