---
title: "Gastroesophageal Care Team"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient_education/)"
    css: "lci_styles.css"
    theme: default
    echo: false
    output-file: ge_care_team_slides.html
  pdf:
    documentclass: scrartcl
  html: default
editor: visual
bibliography: zotero.bib
from: markdown+emoji
---

I’m Dr Jonathan Salo, a GI Cancer Surgeon in Charlotte, North Carolina. If you or someone close to you has been diagnosed with esophageal cancer, this video is for you. In this video, you will learn about

-   The esophageal cancer care team
-   Four different categories of esophageal cancer
-   How the cancer stage helps make treatment decisions

------------------------------------------------------------------------

These videos were designed to help my patients understand their cancer and its treatment.

The internet is a great tool for learning, including learning about cancer.

But when you or a family member receives a new diagnosis of cancer, it's important that you receive information that is specifically tailored to your situation.

------------------------------------------------------------------------

# Care Team

The care of esophageal cancer takes a whole team working together to give you the best care. Let’s take a look at the different team members:

------------------------------------------------------------------------

Gastroenterologist works with an endoscope, which is a flexible tube which inserted through the mouth into the esophagus. The gastroenterologist may perform one of several procedures in your care:

------------------------------------------------------------------------

Upper endoscopy to examine the inside of the esophagus and stomach and biopsy any concerning areas

Endoscopic ultrasound is used in some cases to carefully examine the depth of invasion of a tumor in the esophagus or stomach

------------------------------------------------------------------------

A gastroenterologist may also treat small cancers of the esophagus and stomach with endoscopic therapy such as an endoscopic mucosal resection

------------------------------------------------------------------------

# Diagnostic radiologist

Interpret CT or PET scans Perform biopsies under the guidance of CT or ultrasound

------------------------------------------------------------------------

# Medical Oncologist

Treat cancer with chemotherapy or immunotherapy, using drugs given intravenously (and sometimes by pill).

------------------------------------------------------------------------

# Radiation Therapist

Treats cancer with high-energy x-rays that target tumors in the esophagus and nearby lymph nodes. A radiation therapist can also be referred to as a radiation oncologist.

------------------------------------------------------------------------

# Surgeon

Perform surgery to remove the cancer in the esophagus and surrounding lymph nodes and reconstruct the gastrointestinal tract.

A surgeon may also place a feeding tube if needed, and place a central venous port for chemotherapy.

------------------------------------------------------------------------

# Dietitian

For patients with esophageal cancer, getting adequate nutrition can be a challenge. Frequently the tumor itself can make it difficult to swallow. In addition, cancer therapy can affect your appetite. Some patients will require a temporary feeding tube to help with their nutrition.

In all these cases, a dietitian can help you make sure that your body receives the nutrition it needs.

------------------------------------------------------------------------

# Nurses

In every step along the way in your journey with esophageal cancer, there will be nurses who will help implement the treatment plan. They are a great source of information for any questions that arise during your treatment.

------------------------------------------------------------------------

# Support Staff

The diagnosis of esophageal cancer affects more than just the esophagus - It affects the whole person and the whole family. Most cancer centers will have a wide variety of services to help you and your family navigate the process. Some examples:

-   Counselors and psychologists to help with
-   Financial counselors
-   Palliative Care team to help with symptom control

Don't be afraid to ask about resource which may be available at your cancer center.

------------------------------------------------------------------------

# Your personal team

These are perhaps the most important members of your treatment team. They are family members, friends or neighbors who can help you on this journey you are about to begin. You may find that you will need some help from time to time during your treatment for esophageal cancer. Please don't be afraid to ask for help - you may be surprised at how willing the people close to you are to help.

It can also be very helpful to find someone close to you who can come with you to medical appointments. It can be very helpful to have an extra set of eyes and ears to make sure there is good communication with your care team.

------------------------------------------------------------------------

# Treatment Options

The next video discusses Treatment Options for esophageal cancer.

[Esophageal Cancer Treatment Options](04-Eso_Rx_Options.html)

------------------------------------------------------------------------

We hope you have found this video helpful. This videos and others like it are designed to educate patients and families about esophageal cancer and equip them for their discussions with their esophageal cancer care team.

As always, these videos are no substitute for expert medical advice.

------------------------------------------------------------------------

Feel free to leave a comment or a question, or if you have suggestions for future videos.

------------------------------------------------------------------------
