---
title: "Gastrostomy"
format: 
  docx:
    number-sections: true
    number-depth: 2
  html:
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true
    number-depth: 2
editor: visual
from: markdown+emoji
---


I’m Dr Jonathan Salo, I’m a GI Cancer Surgeon in Charlotte, North Carolina.

Esophageal cancer can cause difficulty with eating, which can limit your body’s ability to get the nutrition you need in order to keep your body healthy during cancer treatment.

In some cases, a feeding tube is needed in order to maintain adequate nutrition. There are two types of feeding tubes:

- Gastrostomy tubes are placed into the stomach. These are also referred to as "G-Tubes"
- Jejunostomy tubes are placed into the jejunum, the first portion of the small intestine. These are also referrred to as "J-Tubes"

Your surgeon and cancer care team will recommend one tube or another.  

The topic of this video is gastrostomy, or G-Tubes


In this video you’ll learn about

-   Gastrostomy tube placement
-   Feeding with a gastrostomy tube
-   Feeding tube care


Normally, food passes from the mouth into the esophagus, and then into the stomach. The stomach serves as a reservoir for food, to allow you to eat a big Thanksgiving. The stomach starts digestion, and then after the meal slowly allows small portions of food to pass into the small intestines, where most of the digestion occurs.

A gastrostomy tube is placed into the stomach, so it is ideal for patients that have tumor in the esophagus or the top of the stomach. A gastrostomy tube is also ideal for patients with difficulty swallowing due to neurological diseases such as ALS.

There are several methods for tube placement for gastrostomy tubes:

- Under fluoroscopy by a radiologist.  In this technique, a temporary tube is passed through the nose into the esophagus and then the stomach.  Air in then injected through the tube in order to fill the stomach. X-rays are then taken to see the air in the stomach. The skin is cleansed and local anesthetic injected into the skin of the abdominal wall. A needle is passed into the stomach, and a tube is then placed through this area.

The advantages of the fluoroscopic technique is that is does not require surgery. This techinique does require that the stomach lie in the correct position just underneath the skin. A CT scan is commonly performed prior to a fluoroscopic gastrostomy tube to confirm the position of the stomach.

An alternative is a percutaneous endoscopic gastrostomy technique, or PEG.

In this technique, an endoscope is passed through the mouth into the stomach.  An needle is then passed through the skin into the stomach, and a tube brought into place.

For patients with cancer of the esophagus or gastroephageal junction who may eventually need surery, things get a bit complicated.

In most cases, when surgery is performed to remove a cancer of the esophagus or gastroesophageal junction, a new esophagus is fashioned from the stomach.  A gastrostomy tube is *also* placed into the stomach. There is a small but real risk that a gastrostomy tube might cause damage to the stomach that would make it more difficult to construct a new esophagus from the stomach.

for patients that may require surgery in the future, 

d



For patients with cancer of the esophagus or stomach, the most common feeding tube is a jejunostomy tube



For patients with cancer of the esophagus, there are two different kinds of feeding tube which can be used:

A gastrostomy tube is placed into the stomach

A jejunostomy tube is placed in the small intestines

Your dietitian and physician will help you decide which tube is best for your situation



Gastrostomy tube

• Placed into stomach

Jejunostomy tube

• Placed into small intestine



Feeding Gastrostomy

A gastrostomy tube allows feeding with a syringe, which can be done several times per day.

When it’s not being used, the gastrostomy tube can be hidden underneath clothing.

For patient who later need surgery on the esophagus, it will be necessary to remove the

gastrostomy tube and place a jejunostomy tube, as the stomach frequently used to create a new

esophagus



A gastrostomy tube can be placed either by endoscopy, which is called a PEG tube

A gastrostomy tube can also be placed by laparoscopy, which is usually preferred if

surgery on the esophagus is planned in the future.

Your surgeon will help you decide which kind of tube is best for you. This is especially important if you will need esophageal surgery in the future, as the stomach is frequently used to make a new esophagus



A gastrostomy tube is generally placed as an outpatient, which means you can go home the same day.

In some cases, a central venous port for chemotherapy is placed at the same time as a gastrostomy tube.



The other type of feeding tube is a jejunostomy.

A jejunostomy tube tube is placed into the small intestines. Because the small intestine is used to receiving food in small quantities, a jejunostomy tube requires the use of a pump to deliver feedings gradually over a matter of hours.

In general, feedings are done at night in order to allow you to be active during the day



A jejunostomy tube is used in cases where it’s not possible to place a gastrostomy tube, such as when there is a tumor in the stomach. A jejunostomy tube is routinely used after esophageal surgery, so in patients who need help with nutrition prior to surgery, it makes sense to put in a jejunostomy tube before surgery. The same tube can then be used for nutrition both before and after surgery.
