---
title: "Images"
---

## Images for Patient Education

https://deidt7p41jzcy.cloudfront.net/EMRF_ai.jpg

### Transparent Background

| Name              | Size    |        Description | 
|:-------------------|:------:|:-------------------------:|
|[Balloon_catheter_Zeichenfläche 1.pgn](https://deidt7p41jzcy.cloudfront.net/Balloon_catheter_Zeichenfläche 1.png)|507.5 KBTwo RFA Balloons||
|[barrx-360-rfa-balloon-catheter-f-big.jpg](https://deidt7p41jzcy.cloudfront.net/barrx-360-rfa-balloon-catheter-f-big.jpg)|102.0 KB|May be commercial|
|[central-venous-port_Zeichenfläche 1.png](https://deidt7p41jzcy.cloudfront.net/central-venous-port_Zeichenfläche 1.png)|173.1 KBCV Port sideview||
|[egd8_ai.png](https://deidt7p41jzcy.cloudfront.net/egd8_ai.png)|50.8 KB|EGD cf eso3_ai.png|
|[EMRF_ai.jpg](https://deidt7p41jzcy.cloudfront.net/EMRF_ai.jpg)|1.2 MB|EMR Favorable (with eso wall)|
|[EMRU_ai.jpg](https://deidt7p41jzcy.cloudfront.net/EMRU_ai.jpg)|1.2 MB|EMR Unfavorable (with eso wall)|
|[Eso_IvorLewis_Anastomosis.png](https://deidt7p41jzcy.cloudfront.net/Eso_IvorLewis_Anastomosis.png)|242.0 KB|Labels for Anastomosis|
|[Eso_IvorLewis_jejunostomy_pancreas.png](https://deidt7p41jzcy.cloudfront.net/Eso_IvorLewis_jejunostomy_pancreas.png)|268.2 KB||
|[Eso_IvorLewis_jejunostomy.png](https://deidt7p41jzcy.cloudfront.net/Eso_IvorLewis_jejunostomy.png)|251.3 KB||
|[Eso_IvorLewis_Leak.png](https://deidt7p41jzcy.cloudfront.net/Eso_IvorLewis_Leak.png)|238.9 KB||
|[Eso_IvorLewis_simple.png](https://deidt7p41jzcy.cloudfront.net/Eso_IvorLewis_simple.png)|211.6 KB|No labels|
|[Eso_McKeown_MIE.png](https://deidt7p41jzcy.cloudfront.net/Eso_McKeown_MIE.png)|218.6 KB||
|[Eso_McKeown_Open.png](https://deidt7p41jzcy.cloudfront.net/Eso_McKeown_Open.png)|225.9 KB||
|[Eso_MIE_McKeown_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_MIE_McKeown_ai.png)|100.5 KB||
|[Eso_MIE_THE_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_MIE_THE_ai.png)|104.5 KB||
|[Eso_Resection1_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_Resection1_ai.png)|108.4 KB|Eso + Tumor + nodes|
|[Eso_Resection2_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_Resection2_ai.png)|117.0 KB||
|[Eso_Resection3_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_Resection3_ai.png)|94.6 KB||
|[Eso_ResectionTotalb_ai.png](https://deidt7p41jzcy.cloudfront.net/Eso_ResectionTotalb_ai.png)|79.7 KB||
|[Eso_tumor_100_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_tumor_100_1600.png)|79.7 KB||
|[Eso_tumor100_resection3_1600.png ](https://deidt7p41jzcy.cloudfront.net/Eso_tumor100_resection3_1600.png )|79.7 KB||
|[Eso_tumor80_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_tumor80_1600.png)|79.7 KB||
|[Eso_tumor60_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_tumor60_1600.png)|79.7 KB||
|[Eso_tumor40_1600.png ](https://deidt7p41jzcy.cloudfront.net/Eso_tumor40_1600.png )|79.7 KB||
|[Eso_tumor20_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_ResectionTotalb_ai.png)|79.7 KB||
|[Eso_Tumor_00_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_Tumor_00_1600.png)|79.7 KB||
|[Eso_tumor00_resection1_1600.png](https://deidt7p41jzcy.cloudfront.net/Eso_tumor00_resection1_1600.png)|79.7 KB||
|[Eso_tumor00_resection2_1600.png ](https://deidt7p41jzcy.cloudfront.net/Eso_tumor00_resection2_1600.png )|79.7 KB||
|[Eso_tumor00_resection4_1600.png ](https://deidt7p41jzcy.cloudfront.net/Eso_tumor00_resection4_1600.png )|79.7 KB||
|[Eso_THE_MIE.png](https://deidt7p41jzcy.cloudfront.net/Eso_THE_MIE.png)|214.7 KB||
|[Eso_TotalEsophagectomy.png](https://deidt7p41jzcy.cloudfront.net/Eso_TotalEsophagectomy.png)|214.2 KB||
|[eso1_ai.png](https://deidt7p41jzcy.cloudfront.net/eso1_ai.png)|103.2 KB||
|[eso2_ai.png](https://deidt7p41jzcy.cloudfront.net/eso2_ai.png)|105.7 KB||
|[eso3_ai.png](https://deidt7p41jzcy.cloudfront.net/eso3_ai.png)|120.7 KB||
|[eso4_ai.png](https://deidt7p41jzcy.cloudfront.net/eso4_ai.png)|122.4 KB||
|[EUS_ai.png](https://deidt7p41jzcy.cloudfront.net/EUS_ai.png)|114.2 KB||
|[gastro-tube_Zeichenfläche 1.pn](https://deidt7p41jzcy.cloudfront.net/gastro-tube_Zeichenfläche 1.png)|167.9 KB||
|[gj_ai.png](https://deidt7p41jzcy.cloudfront.net/gj_ai.png)|121.3 KB||
|[gtube_ai.png](https://deidt7p41jzcy.cloudfront.net/gtube_ai.png)|112.9 KB||
|[HGD_ai.jpg](https://deidt7p41jzcy.cloudfront.net/HGD_ai.jpg)|1.1 MB||
|[images.png](https://deidt7p41jzcy.cloudfront.net/images.png)|1.9 KB||
|[jtube_ai.png](https://deidt7p41jzcy.cloudfront.net/jtube_ai.png)|114.2 KB||
|[JTubeNativeStomach.jpg](https://deidt7p41jzcy.cloudfront.net/JTubeNativeStomach.jpg)|247.5 KB||
|[JTubePostEsophagectomy.jpg](https://deidt7p41jzcy.cloudfront.net/JTubePostEsophagectomy.jpg)|243.4 KB||
|[Lapscope_ai.png](https://deidt7p41jzcy.cloudfront.net/Lapscope_ai.png)|78.9 KB||
|[liverlung_ai.png](https://deidt7p41jzcy.cloudfront.net/liverlung_ai.png)|136.9 KB||
|[liverlung2_ai.png](https://deidt7p41jzcy.cloudfront.net/liverlung2_ai.png)|118.1 KB||
|[T1a_ai.jpg](https://deidt7p41jzcy.cloudfront.net/T1a_ai.jpg)|1.1 MB||
|[t1a_ai.png](https://deidt7p41jzcy.cloudfront.net/t1a_ai.png)|2.7 MB||
|[t1a1b_ai.png](https://deidt7p41jzcy.cloudfront.net/t1a1b_ai.png)|2.8 MB||
|[T1b_ai.jpg](https://deidt7p41jzcy.cloudfront.net/T1b_ai.jpg)|1.1 MB||
|[t1bt2_ai.png](https://deidt7p41jzcy.cloudfront.net/t1bt2_ai.png)|2.9 MB||
|[T2_ai.jpg](https://deidt7p41jzcy.cloudfront.net/T2_ai.jpg)|1.2 MB||
|[t2n0_ai.png](https://deidt7p41jzcy.cloudfront.net/t2n0_ai.png)|2.8 MB||
|[T2T3_5000.jpg](https://deidt7p41jzcy.cloudfront.net/T2T3_5000.jpg)|4.0 MB||
|[T2T3.png](https://deidt7p41jzcy.cloudfront.net/T2T3.png)|1.4 MB||
|[T3_ai.jpg](https://deidt7p41jzcy.cloudfront.net/T3_ai.jpg)|1.2 MB||
|[t3n01_ai.png](https://deidt7p41jzcy.cloudfront.net/t3n01_ai.png)|3.1 MB||
|[tte1_ai.png](https://deidt7p41jzcy.cloudfront.net/tte1_ai.png)|94.3 KB||
|[tte2_ai.png](https://deidt7p41jzcy.cloudfront.net/tte2_ai.png)|86.0 KB||
|[tte3_ai.png](https://deidt7p41jzcy.cloudfront.net/tte3_ai.png)|95.0 KB||
|[tumor_full.png](https://deidt7p41jzcy.cloudfront.net/tumor_full.png)|4.1 MB||
|[tumor1_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor1_ai.png)|2.9 MB||
|[tumor21_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor21_ai.png)|2.9 MB||
|[tumor22_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor22_ai.png)|3.0 MB||
|[tumor23_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor23_ai.png)|3.0 MB||
|[tumor24_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor24_ai.png)|3.1 MB||
|[tumor25_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor25_ai.png)|3.1 MB||
|[tumor25a_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor25a_ai.png)|3.2 MB||
|[tumor25b_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor25b_ai.png)|3.3 MB||
|[tumor3N0_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3N0_ai.png)|2.9 MB||
|[tumor3N13_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3N13_ai.png)|3.0 MB||
|[tumor3T1_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3T1_ai.png)|2.9 MB||
|[tumor3T1b_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3T1b_ai.png)|2.9 MB||
|[tumor3T2_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3T2_ai.png)|3.1 MB||
|[tumor3T3A_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3T3A_ai.png)|3.3 MB||
|[tumor3T4_ai.png](https://deidt7p41jzcy.cloudfront.net/tumor3T4_ai.png)|3.5 MB||
|[tumors_2160.jpg](https://deidt7p41jzcy.cloudfront.net/tumors_2160.jpg)|1.5 MB||
|[tumors_5000.jpg](https://deidt7p41jzcy.cloudfront.net/tumors_5000.jpg)|4.2 MB||
|[tumors_ai.jpg](https://deidt7p41jzcy.cloudfront.net/tumors_ai.jpg)|1.3 MB||
|[wbg_ai.png](https://deidt7p41jzcy.cloudfront.net/wbg_ai.png)|297.6 KB||
|[wbgb_ai.png](https://deidt7p41jzcy.cloudfront.net/wbgb_ai.png)|297.6 KB||

