---
title: "LCI Introduction"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient_education/)"
    css: "lci_styles.css"
    theme: default
    echo: false
    #output-file: lci_intro_slides.html
  pdf:
    documentclass: scrartcl
  html: default
  docx:
    number-sections: true
    number-depth: 3
editor: visual
bibliography: zotero.bib
from: markdown+emoji
---

## 1 - Taking Head 

I'm Dr Jonathan Salo, a GI Cancer Surgeon at the Levine Cancer Institute.

If you’re seeing this video, it’s likely because you have an upcoming consultation scheduled with us.

You may have a recent diagnosis of cancer or you may have a friend or family member who is seeing us

Whatever your situation, we have a great team of people who can help you every step of the way.

## 2 - Surgeons

We have three surgeons in the GI Surgical Oncology Section at the Levine Cancer Institute:

-Joshua Hill
-Hart Squires
-Jonathan Salo


## Location

We’re located at 1310 East Morehead Street in Building 2 of Levine Cancer Institute.

There is a traffic circle which allows you to pull in for patient drop-off

You can either self-park in the garage, or we have free valet parking.

## My Atrium Portal

In order to prepare for your visit, please download the MyAtrium Patient Portal if you have not done so already.

In order to sign up, navigate with your desktop computer or cell phone of my.atriumhealth.org

##

There are smartphone apps for both iPhone and Android

We have a toll-free number for technical support to help you get started.

##

The My Atrium Portal allows you to 

- Send messages to your care team 
- request medication renewals 
- View upcoming appointments 

## Consultation

During your consultation, we will review your case and the information that has been collected so far. We may need to do a physical exam of your heart and lungs, so please wear comfortable clothing.

## After Visit

After your visit, a **After Visit Summary** will be sent to your patient portal, which will provide details of your visit and will outline the next steps in your care

## Consultation Note

We will also send a **consultation note** to you other physicians, so please bring with you the names of other physicians

We typically send notes to:

- Primary care provider
- Referring Physician
- Cardiologist
- Gastroenterologist
- Other Cancer Providers

## Next Steps

Those next steps may include additional x-rays

- CT scan or 
- PET scan 


## Next Steps 2
- An endoscopic procedure 
- Placement of a feeding tube for nutrition if you are having difficulty with eating 
- Placement of a port for chemotherapy 
- Making a referral for chemotherapy or radiation therapy
- Scheduling surgery

## Resources

We recognize that a cancer diagnosis affects not only the patient but the whole community of family and friends. We have a lot of resources to help patients and the people close to them.

-   Support groups for patients and families
-   Counseling to help with stress reduction
-   Financial counselors and social workers to help with insurance and other financial issues
- Social Workers to help find resources
- Supportive Oncology department to help with managing symptoms

## More Resources

- We have a full-time staff of **dietitians**
- We have an **Integrative Oncology** program which and can assist you in choosing supplements and complementary therapies to help manage symptoms and promote wellness without interfering with your cancer treatment.
- We have a **senior oncology clinic** which can help with the special needs of our patients over age 75
- For patients with colon cancer under age 55, we have an **Empower program** to address the special needs of this group.
- We have team of **Nurse Navigators** who can help to coordinate your care by the cancer care team 

## Please bring

When you come for a consultation, please bring with you

-   Names of your physicians
-   A List of your medications
-   A copy of your insurance cards
- Reports you have have of any procedures or scans
-   List of any questions you may have

##  (Talking Head)

Please plan to arrive about 15 minutes before your appointment

-   to fill out any paperwork needed
-   and to fill out a health summary prior to your visit

We will look forward to meeting you.

## Contact

If you have any questions please feel free to contact us at (980) 442-6410

## (Outro Slide)
 