## Cancer Care Team - Physicians

Primary Care Provider (PCP)

Gastroenterologist

Medical Oncologist (chemotherapy)

Radiation Oncologist (if needed)

Surgeons

- Jonathan Salo MD
- Kelli Salter MD
- Michael Roach MD

## Cancer Care Team

Physician's Assistant - Kate Duncan PA-C 

Dietitian - Liz Koch RN

Nurses 

- Matthew Carpenter RN
- Brandon Galloway LPN

Care Coordinator - Karen Julian-Martinez

Nurse Navigators 

- Laura Swift RN
- Lorna Espinal RN

??include social workers and financial counselors?

## Esophagectomy for Cancers of the Esophagus or GE Junction


Primary Surgery

- Superficial Tumors (T1) not completely removed by endoscopy
- Localized Tumors (T2 N0 M0)

Preoperative Therapy $\rightarrow$ Surgery

- Locally Advanced (T3 Nx M0)

## Preparation for Surgery

Medical evaluation may be needed before surgery:

- Pulmonary Function Tests to test lung function
- Cardiology evaluation to test heart function
  - Echocardiogram
  - Stress Test
  - Holter monitor
  

## Preoperative Visits

Medical Oncology - Monitor chemotherapy and side effects

Radiation Oncology - Monitor radiation and side effects

Surgical Oncology

- Consult visit with Dr Salo
- Mid-treatment visits with Dr Salo / Kate Duncan
- Preop visit with Dr Salo (may be virtual)
- In-person preop visit with Kate Duncan and Liz Koch
  
  
## Nutrition Prior to Surgery

High-protein diet (most people need 60-80 grams protein/day)

  - Protein shakes (Permier or Fairlife) with protein and minimal sugar
  
Important to avoid weight loss prior to surgery

Good nutrition before surgery improves wound healing and recovery
  
  
## Exercies Prior to Surgery

Goal: 30minutes/day of vigorous exercise 6 days/week

Vigorous: Working hard enough you can't carry a conversation

Types of Exercise:

- Walking: Outside, Treadmilll, or an indoor Mall
- Stationary Exercise Bike

Lifting light weights and stretching are helpful in addition

