## Locally-advanced Adenocarcinoma

"Sandwich" chemotherapy before + after surgery:

Chemo (8 wks) $\rightarrow$ Surgery $\rightarrow$ Chemo (8 wks)

::: fragment
Two different drug combinations:
:::

::: fragment
-   FLOT (more effective)
:::

::: fragment
-   FOLFOX (better tolerated)
:::

## "Sandwich" Chemotherapy Drugs

::::: columns
::: {.column width="40%"}
**FLOT**

-   5-FU
-   Leucovorion
-   Oxaliplatin
-   Taxotere
:::

::: {.column width="60%"}
**FOLFOX**

-   5-FU
-   Leucovorin
-   Oxaliplatin
:::
:::::

## FLOT Treatment Plan

-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)
-   Surgery (4-6 weeks later)
-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)

## Immunotherapy

Immunotherapy is a form of cancer treatment that stimulates your immune system to fight cancer.

Some cancer cells will turn off immune cells using a protein called PD-L1. Immunotherapy can counteract this "off signal" and gives immune cells a "turn on signal" so that they fight cancer.

Darvalumab is an immunotherapy drug that fights cancers by counteracting PD-L1

## Matterhorn Trial

The Matterhorn clinical trial compared two types of treatment:

FLOT x 4 doses -\> Surgery -\> FLOT x 4 doses

FLOT + Durvalumab -\> Surgery -\> FLOT + Durvalumab -\> Durvalumab

Better survival with addition of durvalumab

## FLOT± Durvalumab

::::: columns
::: {.column width="50%"}
**FLOT**

-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)
-   Surgery (4-6 weeks later)
-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)
:::

::: {.column width="50%"}
**FLOT + Durvalumab**

-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)
    -   Durvalumab 2 doses
-   Surgery (4-6 weeks later)
-   FLOT Chemo every 2 weeks x 4 (=8 weeks total)
  -   Durvalumab 2 doses
-   Durvalumab 10 doses every month
:::
:::::

## Matterhorn Trial

The Matterhorn clinical trial compared two types of treatment:

FLOT x 4 doses -\> Surgery -\> FLOT x 4 doses

FLOT + Durvalumab -\> Surgery -\> FLOT + Durvalumab -\> Durvalumab

Better survival with addition of durvalumab

**Treatment with durvalumab depends upon approval from insurance company**