## Day Prior to Surgery

- Clear liquids for dinner evening prior
- You will receive instructions regarding medicines
- Stop tube feeds at midnight night before

## Morning of Surgery

Unless instructed otherwise:

- *Arrival* time is usually 2-3 hours before the *surgery* time.
  - Monday, Tuesday, Wednesday, Friday: Arrive 4am
  - Thursday: Arrive 5am
- Nothing to eat or drink after midnight

## Medicines the Morning of Surgery

- Medicines with a sip of water or *black* coffee
- No milk or cream
- Surgery will be cancelled if you take milk or cream the morning of surgery

## Hospitality House

- Guest house for patients and families
- Located walking distance from hospital
- Shuttle service available
- Make reservation request through clinic nurses
- Cost \$50 per night

## Parking and Arrival

- Blue Parking Deck: 1716 Medical Center Drive, Charlotte NC 28204
- Patient Drop Off: 1096 Blythe Blvd, Charlotte NC 28204
- Dixon Tower entrance(Traffic circle with Fountains)
- Check in and tell them you will have surgery
- Staff will escort you to the Preoperative area on 5th floor

## Day of Surgery

- Waiting Room on 5th floor for families
- Surgery completed 3pm - 5pm
- Transfer to Surgical Intensive Care Unit 4pm - 6pm
- Visitors permitted into the ICU 5pm - 7pm

## What to Bring to the Hospital

- No jewelery or valuables
- Cell phone and charger
- Insurance cards
- Underwear you don't mind discarding

## Visitor's Policy

Intensive Care Unit

- Two visitors at a time 8am - 8pm
- One "Care Partner" can stay overnight in ICU

Ward

- All rooms are private rooms
- Day bed available for a family member
- Visiting hours 8am - 8pm

No visitors please who have a cough or fever!
