## Chemotherapy + Radiation CROSS Trial

363 patients with esophageal cancer studied

Patients were treated in two groups:

**Surgery Alone**

vs

**Chemo + Radiation** $\rightarrow$ Surgery

## Chemotherapy + Radiation CROSS Trial

363 patients with esophageal cancer studied

Chemotherapy + radiation together over 6 wks

**Surgery Alone**

vs

**Chemo + Radiation**$\rightarrow$Surgery $\Rightarrow$ Longer Survival

::: {.content-hidden unless-format="docx"}
The results were quite dramatic: The group that was treated with all three therapies, chemotherapy and radiation and surgery, lived on average twice a long as patients who had surgery alone.
:::

## Chemo + Radiation CROSS Trial

Typical schedule for chemotherapy + radiation:

-   Chemotherapy once per week for six weeks
-   Radiation five days per week for six weeks (28)

::: {.fragment}
-   PET scan (or CT) 4 weeks after the end of radiation
:::

::: {.fragment}
-   Surgery 8 weeks after the end of radiation
:::

## Chemo + Radiation - Side Effects

Kills cancer cells in the esophagus and lymph nodes

Can also irritate the lining of the esophagus.

::: {.fragment}
Swallowing can be difficult the last 2 weeks.
:::

::: {.fragment}
Feeding tube may be needed for hydration/nutrition.
:::