---
title: "GI Stromal Tumors of the Stomach"
format: 
  pptx: 
    reference-doc: template.pptx
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[LCI GI Oncology](https://jcsalo.github.io/patient_education/LCI.html)"
    css: "lci_styles.css"
    theme: [simple, lci.scss]
    echo: false
    transition: fade
    #output-file: lci_esot3_slides.html
    pdf-separate-fragments: true
  html: default
  docx:
    number-sections: true
    number-depth: 3
editor: visual
bibliography: zotero.bib
---

## GI Stromal Tumors

-   Arise from the wall of the stomach
-   Grow slowly over time
-   Lymph nodes rarely involved
-   Not conventional stomach cancer

## GIST vs Adenocarcinoma

::::: columns
::: {.column width="40%"}
**GIST**

-   Starts from wall of stomach
-   Slow growing
-   Rarely spreads to lymph nodes
:::

::: {.column width="60%"}
**Adenocarcinoma**

-   Conventional "stomach cancer"
-   Starts from lining of stomach
-   Can spread to lymph nodes
-   More aggressive
:::
:::::

## GIST: Benign or Malignant?

GIST tumors have a range of behavior:

-   Small tumors tend to behave in a benign manner but can grow over time
-   Larger tumors tend to behave in a malignant (cancerous) manner

## GIST Treatment

-   Initial treatment usually surgery
-   Risk of recurrence determined by pathology
-   Size of tumor
-   Mitotic rate = how rapidly tumor is dividing

## Imatinib = Gleevec

-   Oral drug shrinks GIST tumors
-   Well tolerated
-   Given *after* surgery for high-risk tumors
    -   1 or 3 years depending upon risk
-   Given *before* surgery for large tumors

{{< include lci_gastrectomyt3_guts.qmd >}}

{{< include lci_treatment_prep_guts.qmd >}}

{{< include lci_staff_guts.qmd >}}