
## Anesthesia

Epidural catheter usually placed for pain control

- Remains in place for 2-5 days
- Dosage can be adjusted as needed
- Can make it more difficult to urinate
- May require foley catheter in bladder
- Foley catheter removed after epidural removed


## ICU Stay

Multiple lines and tubes:

- NG tube in nose to drain stomach and esophagus
- Catheter in bladder
- Chest tube right chest
- Abdominal drains (usually 2)
- Feeding jejunostomy (usually says in 8 wks)

## Ward - 6Tower

- Jejunostomy feeding
- Up in a chair most of the day
- Walking in the halls
  - Start with assistance
  - Improves lung function
  - Prevents loss of muscle


## Jejunostomy Feeds

Jejunostomy tube feeds
- Start continuous (24 hours)
- Convert to night-time only (16 hours)

Water administered through feeding tube
- Usually 8oz 4 times/day
- Important to prevent dehydration

Diabetic patients may need insulin

## Jejunostomy Feeds with Diabetes

Jejunostomy feedings may cause blood sugars to be elevated
- Insulin may be required along with feeds

Typical Pattern for tube feeds
- Feeds run via pump from 6pm to 10am
- Insulin at 6pm (70/30 insulin)
- Insulin at Midnight (70/30 insulin)
- No insulin if tube feedings are not run

## Nasogastric (NG) Tube

Tube passed through nose into stomach
- Drains fluid from stomach
- Prevents vomiting

Upper GI X-ray on 2nd or 3rd day after surgery
- If stomach empties well $\rightarrow$ NG tube removed
- Otherwise, X-ray repeated 2-3 days later

## Swallowing Evaluation

Once NG tube has been removed:

Modified barium swallow in radiology

- 70% of patients $\Rightarrow$ liquids started by mouth


## Discharge

Goal: ready to leave day #6 after surgery

- Night-time tube feedings (6pm to 10am)
- Some nutrition by mouth (70% of patients)
  - 1 oz of water per hour by mouth  OR
  - Protein shakes 4oz every 2 hours in some 
- Water through tube 8oz four times per day
- Home care nursing (feeding tube teaching)
- Home infusion (tube feeding supplies)

