---
title: "LCI Introduction"
format: 
  revealjs:
    slide-number: c/t
    width: 1280
    height: 720
    logo: "atriumlogo.jpg"
    footer: "[Patient Education](https://jcsalo.github.io/patient_education/)"
    css: ["lci_styles.css"]
    theme: default
    echo: false
  pdf:
    documentclass: scrartcl
editor: visual
bibliography: zotero.bib
---

## LCI welcome 2024 {style="font-size: 1.5em; text-align: left"}

I'm Dr Jonathan Salo, a GI Cancer Surgeon at the Levine Cancer Institute.

If you’re seeing this video, it’s likely because you have an upcoming consultation scheduled with us.

You may have a recent diagnosis of cancer.

Whatever your situation, we have a great team of people who can help you every step of the way.

## Location

We’re located at 1310 East Morehead Street in Building 2 of Levine Cancer Institute.

There is a traffic circle which allows you to pull in for patient drop-off

You can either self-park in the garage, or we have free value parking.

## My Atrium Portal

In order to prepare for your visit, please download the MyAtrium Patient Portal if you have not done so already.

The My Atrium Portal allows you to View your medical records Send a messages to your care team and request medication renewals You can view your upcoming appointments and procedures or x-rays

In order to sign up, navigate with your desktop computer or cell phone of my.atriumhealth.org

There are smartphone apps for both iPhone and Android

We have a toll-free number for technical support to help you get started.

## Consultation

During your consultation, we will review your case and the information that has been collected so far. We may need to do a physical exam of your heart and lungs, so please wear comfortable clothing.

## Next Steps

Those next steps may include: Additional xrays, such as a CT scan or PET scan An endoscopic procedure Placement of a feeding tube for nutrition if you are having difficulty with eating Placement of a port for chemotherapy Scheduling for surgery Making a referral for chemotherapy or radiation therapy

## After Visit

After your visit, a **After Visit Summary** will be sent to your patient portal, which will provide details of your visit and will outline the next steps in your care

We will also send a **consultation note** to you other physicians, so please bring with you the names of other physicians

## Resources

We recognize that a cancer diagnosis affects not only the patient but the whole community of family and friends. We have a lot of resources to help patients and the people close to them.

-   Support groups for patients and families

-   Counseling to help with stress reduction

-   Financial counselors and social workers to help with insurance and other financial issues

-   Supportive Oncology department to help with managing symptoms

## 

We have a full-time staff of **dietitians**

We have an I**ntegrative Oncology** program which and can assist you in choosing supplements and complementary therapies to help manage symptoms and promote wellness without interfering with your cancer treatment.

We have a **senior oncology clinic** which can help with the special needs of our patients over age 75

For patients with colon cancer under age 55, we have an **Empower program** to address the special needs of this group.

We have team of **Nurse Navigators** who can help to coordinate you care by the cancer care team and locate resources you may need.

## Please bring

When you come for a consultation, please bring with you\

-   A copy of your insurance cards

-   List of your physicians

-   List of your medications

-   List of any questions you may have

## Arrival

Please plan to arrive about 15 minutes before your appointment

-   to fill out any paperwork needed

-   and to fill out a health summary prior to your visit

We will look forward to meeting you.

## Outro

Feel free to subscribe so you can be notified about new videos

If there are video topics you would like us to cover, please leave a comment below.
