---
title: "LCI Introduction"
format: 
  docx:
    number-sections: true
    number-depth: 2
  html:
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true
    number-depth: 2
editor: visual
from: markdown+emoji
---

## Taking Head *1*

I'm Dr Jonathan Salo, a GI Cancer Surgeon at the Levine Cancer Institute.

If you’re seeing this video, it’s likely because you have an upcoming consultation scheduled with us.

You may have a recent diagnosis of cancer or you may have a friend or family member who is seeing us

Whatever your situation, we have a great team of people who can help you every step of the way.

## Surgeons *L* **4**

We have three surgeons in the GI Surgical Oncology Section at the Levine Cancer Institute:

-   Joshua Hill
-   Hart Squires
-   Jonathan Salo. (2)

## Location. **2** 

We’re located at 1310 East Morehead Street in Building 2 of Levine Cancer Institute.  (3)

## Location (closeup)

There is a traffic circle which allows you to pull in for patient drop-off

## Photo of LCI 

You can self-park in the adjacent garage (5)

## Photo of Valet

Or you can take advantage of our free valet parking. (6)

##  My Atrium Portal **4**

In order to prepare for your visit, please sign up for the MyAtrium Patient Portal if you have not done so already.

The MyAtrium Portal is similar to MyChart, and is a way that you can access your electronic medical record an communicate with your healthcare team (7)

## My Atrium Portal **4**    

The My Atrium Portal allows you to

-   Send messages to your care team (8)

## - My Atrium Portal   

-   request medication renewals (9)

## - My Atrium Portal 

-   View upcoming appointments (10)

## - My Atrium Portal 

-   Connect for virtual visits (11)

## my.atriumhealth.org

In order to sign up, navigate with your desktop computer or cell phone of my.atriumhealth.org (12)

## My Atrium signup **2**

You can sign up online through a desktop, tablet, or phone (13)

## My Atrium Apps

There are smartphone apps for both iPhone and Android

We have a toll-free number for technical support to help you get started. (14)



## - After Visit Summary **4**

After your visit, an **After Visit Summary** will be sent to your patient portal and will be printed for you, which will provide details of your visit and will outline the next steps in your care. These may include additional procedures or appointments.

## Consultation Notes 

After your consultation, we will send a **consultation note** to you other physicians, so please bring with you the names of other physicians

We typically send notes to:

Primary care provider

Referring Physician

Cardiologist

Gastroenterologist

Other Cancer Providers (16)

## Possible Next Steps 

After your consultation, there are several possible next steps:

-   We may order a PET scan or CT Scan

## - Possible Next Steps 

-   Endoscopic Procedure such as EGD

## - Possible Next Steps 

-   Placement of a feeding tube

## - Possible Next Steps 

-   or a Port for chemotherapy

## - Possible Next Steps 

-   Referrals may be made for chemotherapy or radiation therapy

## - Possible Next Steps 

-   or Surgery will be scheduled (22)

## - Resources 

We recognize that a cancer diagnosis affects not only the patient but the whole community of family and friends. We have a lot of resources to help patients and the people close to them.

-   Support groups for patients and families (23)

## - Resources

-   Counseling to help with stress reduction (24)

## - Resources

-   Financial counselors and social workers to help with insurance and other financial issues (25)

## - Resources

-   Social Workers to help find resources (26)

## - Resources

-   Supportive Oncology department to help with managing symptoms (27)

## - Resources 

-   We have a full-time staff of **dietitians** (28)

## - Resources

-   We have a **senior oncology clinic** which can help with the special needs of our patients over age 75 (29)

## - Resources 

-   For patients with colon cancer under age 55, we have an **Empower program** to address the special needs of this group.

## - Resources

-   We have team of **Nurse Navigators** who can help to coordinate your care by the cancer care team (31)

## Please bring 

When you come for a consultation, please bring with you

-   Names of your physicians (32)

## - Please Bring 

-   A copy of your insurance cards (33)

## - Please Bring 

If you have access to the MyAtrium Health portal, please log in an review your list of medicines (34)

## - Please Bring 

Otherwise, please bring a list of your medicines with you (35)

## - Please Bring 

- Reports of any procedures you may have had recently

## Please Bring

-   List of any questions you may have (37)

## Please Plan to Arrive **1**

Please plan to arrive 30 minutes before your appointment time to allow time for registration (38)

## Don't Forget

Please don't forget to take advantage of our free valet parking.  We want to do everything we can to make your visit as enjoyable as possible (39)

## We will look forward to meeting you. **1*

We will look forward to meeting you in person.

## Contact **4**

If you have any questions please feel free to contact us at (980) 442-6410. (41)

## Outro **2**
