---
title: "Scripts"
output: html_document
---

[Introduction to LCI](script_lci_intro.qmd)

[Locally-Advanced Adenocarcinoma of the Esophagus](eso_la_adenoca.qmd)



[Gastroesophageal Dx and Staging](ge_dx_staging.qmd)

\[Gastroesophageal Treatment Options\]

[Images](images.html)

### Gastroesophageal Cancer

| Topic | Script | HTML | PDF | Video |
|:--------------|:-------------:|:-------------:|:-------------:|:-------------:|
| LCI Introduction | [Script](script_lci_intro.docx) | [HTML](script_lci_intro.html) | [PDF](script_lci_intro.pdf) | [OLD Video](https://www.youtube.com/watch?v=aDkgurq17wE) |
| GE Diagnosis & Staging | [Script](ge_dx_staging_slides.html) | [HTML](ge_dx_staging.html) | [PDF](ge_dx_staging.pdf) | [OLD Video](https://www.youtube.com/watch?v=aDkgurq17wE) |
| Eso Treatment Options | [Script](eso_rx_options_slides.html) | [HTML](eso_tx_options.html) | [PDF](eso_rx_options.pdf) | [OLD Video](https://www.youtube.com/watch?v=Tk8cp3uL-lU) |
| Esophageal Early Stage | [Script](eso_early_slides.html) | [HTML](eso_early.html) | [PDF](eso_early.pdf) |  |
| Eso T2N0 | [Script](eso_t2.docx) | [HTML](eso_advanced.html) | [PDF](eso_advanced.pdf) | [Slides](lci_esot2.htm) |
| Eso T3 | [Script](eso_t3.docx) | [HTML](eso_t3.html) | [PDF](eso_t3.pdf) | [Slides](lci_esot3.htm) |
| Eso Advanced Disease | [Script](eso_advanced_slides.html) | [HTML](eso_advanced.html) | [PDF](eso_advanced.pdf) |  |
| Locally-Advanced ACA | [Script](eso_aca_locally_advanced_slides.html) | [HTML](eso_aca_locally_advanced.html) | [PDF](eso_aca_locally_advanced.pdf) |  |
| Locally-Advanced SCCA | [Script](eso_scca_locally_advanced_slides.html) | [HTML](eso_scca_locally_advanced.html) | [PDF](eso_scca_locally_advanced.pdf) |  |
| GE Metastatic Disease | [Script](ge_metastatic_slides.html) | [HTML](ge_metastatic.html) | [PDF](ge_metastatic.pdf) |  |
| Esophagectomy | [Script](eso_surgery_slides.html) | [HTML](eso_surgery.html) | [PDF](eso_surgery.pdf) |  |
| Your Surgery Team | [Script](surgeon_slides.html) | [HTML](surgeon.html) | [PDF](surgeon.pdf) |  |
| Nutrition | [Script](nutrition_slides.html) | [HTML](nutrition.html) | [PDF](nutrition.pdf) |  |
| Jejunostomy | [Script](jejunostomy_slides.html) | [HTML](jejunostomy.html) | [PDF](jejunostomy.pdf) |  |
| Gastrostomy | [Script](gastrostomy_slides.html) | [HTML](gastrostomy.html) | [PDF](gastrostomy.pdf) |  |
| Exercise | [Script](exercise_slides.html) | [HTML](exercise.html) | [PDF](exercise.pdf) |  |
| Central Venous Port | [script](cv_port_slides.html) | [HTML](cv_port.html) | [PDF](cv_port.pdf) |  |
| GE Care Team | [script](ge_care_team_slides.html) | [HTML](ge_care_team.html) | [PDF](ge_care_team.pdf) |  |
| **OBSELETE** |  |  |  |  |
| Eso Diagnosis & Staging | [Script](eso_dx_staging_slides.html) | [HTML](eso_dx_staging.html) | [PDF](eso_dx_staging.pdf) | [OLD Video](https://www.youtube.com/watch?v=aDkgurq17wE) |
| Barretts Esophagus | [Script](eso_barretts_slides.html) | [HTML](eso_barretts.html) | [PDF](eso_barretts.pdf) |  |
| Eso ACA Treatment | [Script](eso_aca_rx_slides.html) | [HTML](eso_aca_rx.html) | [PDF](eso_aca_rx.pdf) |  |
| Symptoms - Esophageal | [Script](eso_symptoms_slides.html) | [THML](eso_symptoms.html) | [PDF](eso_symptoms.pdf) |  |

## Deprecated

[Eso Dx and Staging](eso_dx_staging.qmd)
